In [2]:
import pandas as pd
df = pd.read_excel("/Users/alinakenzhegariyeva/Desktop/almaty tochki.xlsx")
df.head()

,FID,Shape *,fd1r08p1,rta_date,fd1id,yr,period,area_code,fd1r05p1,fd1r01p1,...,fd1r142p6,fd1r17,type_dtp,fd1r17_des,load_date,fd1r07p1,fd1r061p0,fd1r061p1,fd1r061p2,globalid
0,6165,Point,5,2013-01-15,1900903P20OM0H00002521996,2013,1,1919,19:10:00,13191003600000,...,0,,0,,2022-05-29,заснеженная,,,0.0,{056ea947-c430-4d14-b4c4-7c22f9b0995d}
1,6175,Point,5,2013-01-29,1900903PE0YR4MA0002542272,2013,1,1919,06:50:00,13191003600000,...,0,,0,,2022-05-29,заснеженная,,,0.0,{d7cfe59d-ed6f-411f-9f7b-fe31f42f6562}
2,6179,Point,5,2013-02-05,1900903PP14ZD8T0002560397,2013,2,1919,15:30:00,13191003600000,...,0,,0,,2022-05-29,обледеневшая,,,0.0,{b79ff0e1-8cfd-4aae-a066-fc1b83b30afc}
3,6315,Point,5,2013-02-14,1900903Q6152DJA0002592147,2013,2,1919,17:30:00,13191003600000,...,0,,0,,2022-05-29,обледеневшая,,,0.0,{36b2b608-2d60-4fe2-8482-2b7e3194f606}
4,6316,Point,5,2013-02-20,1900903Q6157CGP0002592168,2013,2,1919,13:00:00,13191003600000,...,0,,0,,2022-05-29,обледеневшая,,,0.0,{78fffe6f-8197-4ccc-b18c-7a6f10d9abd1}

In [3]:
df = df.rename(columns={
    "fd1r08p1": "Type_of_Accident",
    "rta_date": "Accident_Date",
    "fd1id": "Accident_Record_ID",
    "yr": "Year",
    "period": "Month",
    "area_code": "Region_Code",
    "fd1r05p1": "Time_of_Day_of_Accident",
    "fd1r01p1": "Card_Number",

    "fd1r07p2": "Lighting_Conditions",
    "fd1r07p3": "External_Lighting_at_Night",
    "fd1r07p4": "Road_Street_Elements",

    "fd1r071p1": "Recorded_Deficiencies",
    "fd1r071p1_": "Registered_Road_Deficiencies_Description",

    "fd1r09p1": "Traffic_Rule_Violation",

    "fd1r14p1": "At_Fault_Party",
    "fd1r141p1": "Condition_of_At_Fault_Person",
    "fd1r141p1_": "Condition_of_At_Fault_Person_Description",

    "fd1r13p1": "Number_of_Injured",
    "fd1r13p2": "Number_of_Fatalities",

    "fd1r06p1": "Accident_Location",
    "fd1r06p2": "Accident_District",
    "fd1r06p3": "Accident_Location_Settlement",

    "vehicle_ca": "Transport_Category",
    "is_public_": "Public_Transport_Involved",

    "fd1r041p1": "Day_of_Week",

    "fd1r072p1": "Weather_Conditions",
    "fd1r073p1": "Total_Number_of_Lanes",
    "fd1r074p1": "Speed_Limit",

    "fd1r10p1": "Number_of_Vehicles",
    "fd1r142p6": "Gender_of_At_Fault",

    "fd1r17": "Qualification_Code",
    "type_dtp": "Accident_Type",
    "fd1r17_des": "Qualification_Description",

    "load_date": "Upload_Date_to_GIS",

    "fd1r07p1": "Road_Surface_Condition",

    "fd1r061p0": "Highway_Index",
    "fd1r061p1": "Road_Section",
    "fd1r061p2": "Kilometer"

})

In [4]:
# --- Replace duplicates so one region name uses a single existing numeric code ---
# Mapping chosen so that duplicate codes are replaced by the canonical code (one you listed)
district_canonical_map = {
    # map duplicate codes -> canonical codes
    193348: 191960,  # 193348 (Саркандский)  -> 191960 (Саркандский)
    193340: 191946,  # 193340 (Кербулакский) -> 191946 (Кербулаксий)
    193310: 191952,  # 193310 (Карасайский)  -> 191952 (Карасайский)
    193332: 191932,  # 193332 (Аксуский)    -> 191932 (Аксуский)
    193342: 191948,  # 193342 (Коксуский)   -> 191948 (Коксуский)
    193336: 191964,  # 193336 (Ескельдинский)-> 191964 (Ескельдинский)
}

# 1) inspect unique values before
print("Unique District codes before:", sorted(df['Accident_District'].dropna().unique()))

# 2) apply replacements
df['Accident_District'] = df['Accident_District'].replace(district_canonical_map)

# 3) ensure integer dtype (only if appropriate — if NaNs exist and you want ints, fill or use Int64)
# If no NaNs or you want to keep as python int:
# df['District'] = df['District'].astype(int)

# If NaNs may exist and you want nullable integer dtype:
# df['District'] = df['District'].astype('Int64')

# 4) inspect unique values after and counts
print("Unique District codes after: ", sorted(df['Accident_District'].dropna().unique()))
print("\nCounts by District code after mapping:")
print(df['Accident_District'].value_counts().sort_index())

Unique District codes before: [np.int64(191910), np.int64(191916), np.int64(191918), np.int64(191926), np.int64(191932), np.int64(191934), np.int64(191936), np.int64(191940), np.int64(191942), np.int64(191946), np.int64(191948), np.int64(191950), np.int64(191952), np.int64(191956), np.int64(191958), np.int64(191959), np.int64(191960), np.int64(191962), np.int64(191964), np.int64(191966), np.int64(191968), np.int64(193310), np.int64(193318), np.int64(193332), np.int64(193336), np.int64(193340), np.int64(193342), np.int64(193348)]
Unique District codes after:  [np.int64(191910), np.int64(191916), np.int64(191918), np.int64(191926), np.int64(191932), np.int64(191934), np.int64(191936), np.int64(191940), np.int64(191942), np.int64(191946), np.int64(191948), np.int64(191950), np.int64(191952), np.int64(191956), np.int64(191958), np.int64(191959), np.int64(191960), np.int64(191962), np.int64(191964), np.int64(191966), np.int64(191968), np.int64(193318)]

Counts by District code after mapping:
Accident_District
191910    1961
191916    1317
191918     141
191926     111
191932     271
191934     500
191936     227
191940    4312
191942    2450
191946     374
191948     483
191950     220
191952    5569
191956     993
191958     261
191959      69
191960     205
191962    3769
191964     551
191966     475
191968    3854
193318       4
Name: count, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28117 entries, 0 to 28116
Data columns (total 41 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   FID                                       28117 non-null  int64
 1   Shape *                                   28117 non-null  object
 2   Type_of_Accident                          28117 non-null  int64
 3   Accident_Date                             28117 non-null  datetime64[ns]
 4   Accident_Record_ID                        28117 non-null  object
 5   Year                                      28117 non-null  int64
 6   Month                                     28117 non-null  int64
 7   Region_Code                               28117 non-null  int64
 8   Time_of_Day_of_Accident                   28117 non-null  object
 9   Card_Number                               28117 non-null  int64
 10  Lighting_Conditions                       28117 non-null  object
 11  External_Lighting_at_Night                28117 non-null  object
 12  Road_Street_Elements                      28117 non-null  object
 13  Registered_Road_Deficiencies_Description  28117 non-null  object
 14  Recorded_Deficiencies                     28117 non-null  object
 15  Traffic_Rule_Violation                    28117 non-null  object
 16  At_Fault_Party                            28117 non-null  object
 17  Condition_of_At_Fault_Person_Description  28117 non-null  object
 18  Condition_of_At_Fault_Person              28117 non-null  object
 19  Number_of_Injured                         28117 non-null  int64
 20  Number_of_Fatalities                      28117 non-null  int64
 21  Accident_Location                         28117 non-null  object
 22  Accident_District                         28117 non-null  int64
 23  Accident_Location_Settlement              28117 non-null  object
 24  Transport_Category                        28117 non-null  object
 25  Public_Transport_Involved                 28117 non-null  int64
 26  Day_of_Week                               28117 non-null  int64
 27  Weather_Conditions                        28117 non-null  object
 28  Total_Number_of_Lanes                     28117 non-null  int64
 29  Speed_Limit                               28117 non-null  int64
 30  Number_of_Vehicles                        28117 non-null  int64
 31  Gender_of_At_Fault                        28117 non-null  int64
 32  Qualification_Code                        28117 non-null  object
 33  Accident_Type                             28117 non-null  int64
 34  Qualification_Description                 28117 non-null  object
 35  Upload_Date_to_GIS                        28117 non-null  datetime64[ns]
 36  Road_Surface_Condition                    28117 non-null  object
 37  Highway_Index                             28117 non-null  object
 38  Road_Section                              28117 non-null  object
 39  Kilometer                                 28117 non-null  float64
 40  globalid                                  28117 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(16), object(22)
memory usage: 8.8+ MB

In [6]:
df = df.drop(columns=['FID', 'Shape *','globalid'])

In [7]:
df = df.drop(columns=['Upload_Date_to_GIS'])

In [8]:
df.replace(r"^\s*$", pd.NA, regex=True, inplace=True)

In [10]:
df = df.drop(columns=['Region_Code'])

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28117 entries, 0 to 28116
Data columns (total 36 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Type_of_Accident                          28117 non-null  int64
 1   Accident_Date                             28117 non-null  datetime64[ns]
 2   Accident_Record_ID                        28117 non-null  object
 3   Year                                      28117 non-null  int64
 4   Month                                     28117 non-null  int64
 5   Time_of_Day_of_Accident                   28117 non-null  object
 6   Card_Number                               28117 non-null  int64
 7   Lighting_Conditions                       18271 non-null  object
 8   External_Lighting_at_Night                6831 non-null   object
 9   Road_Street_Elements                      5904 non-null   object
 10  Registered_Road_Deficiencies_Description  28112 non-null  object
 11  Recorded_Deficiencies                     28112 non-null  object
 12  Traffic_Rule_Violation                    26337 non-null  object
 13  At_Fault_Party                            28112 non-null  object
 14  Condition_of_At_Fault_Person_Description  26069 non-null  object
 15  Condition_of_At_Fault_Person              26069 non-null  object
 16  Number_of_Injured                         28117 non-null  int64
 17  Number_of_Fatalities                      28117 non-null  int64
 18  Accident_Location                         28117 non-null  object
 19  Accident_District                         28117 non-null  int64
 20  Accident_Location_Settlement              12340 non-null  object
 21  Transport_Category                        21668 non-null  object
 22  Public_Transport_Involved                 28117 non-null  int64
 23  Day_of_Week                               28117 non-null  int64
 24  Weather_Conditions                        19584 non-null  object
 25  Total_Number_of_Lanes                     28117 non-null  int64
 26  Speed_Limit                               28117 non-null  int64
 27  Number_of_Vehicles                        28117 non-null  int64
 28  Gender_of_At_Fault                        28117 non-null  int64
 29  Qualification_Code                        20647 non-null  object
 30  Accident_Type                             28117 non-null  int64
 31  Qualification_Description                 20647 non-null  object
 32  Road_Surface_Condition                    20616 non-null  object
 33  Highway_Index                             2207 non-null   object
 34  Road_Section                              3404 non-null   object
 35  Kilometer                                 28117 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(14), object(20)
memory usage: 7.7+ MB

In [16]:
df = df.drop(columns=['Year', 'Month', 'Day_of_Week'])

In [18]:
df["Year"] = df["Accident_Date"].dt.year
df["Month"] = df["Accident_Date"].dt.month
df["Day_of_Week"] = df["Accident_Date"].dt.dayofweek + 1

In [20]:
df["Year"].unique()

array([2013, 2012, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024, 2025], dtype=int32)

In [21]:
df["Month"].unique()

array([ 1,  2, 12,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [22]:
df["Day_of_Week"].unique()

array([2, 4, 3, 7, 1, 5, 6], dtype=int32)

In [24]:
# Time features (NO conversion needed)
df["Time_of_day_of_accident_hrs"] = df["Time_of_Day_of_Accident"].apply(lambda x: x.hour)

def get_time_of_day(hour):
    if 5 <= hour < 12:
        return 1
    elif 12 <= hour < 17:
        return 2
    elif 17 <= hour < 21:
        return 3
    else:
        return 4

df["Time_of_Day"] = df["Time_of_day_of_accident_hrs"].apply(get_time_of_day)

In [26]:
df = df.drop(columns=['Time_of_Day_of_Accident'])

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28117 entries, 0 to 28116
Data columns (total 37 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Type_of_Accident                          28117 non-null  int64
 1   Accident_Date                             28117 non-null  datetime64[ns]
 2   Accident_Record_ID                        28117 non-null  object
 3   Card_Number                               28117 non-null  int64
 4   Lighting_Conditions                       18271 non-null  object
 5   External_Lighting_at_Night                6831 non-null   object
 6   Road_Street_Elements                      5904 non-null   object
 7   Registered_Road_Deficiencies_Description  28112 non-null  object
 8   Recorded_Deficiencies                     28112 non-null  object
 9   Traffic_Rule_Violation                    26337 non-null  object
 10  At_Fault_Party                            28112 non-null  object
 11  Condition_of_At_Fault_Person_Description  26069 non-null  object
 12  Condition_of_At_Fault_Person              26069 non-null  object
 13  Number_of_Injured                         28117 non-null  int64
 14  Number_of_Fatalities                      28117 non-null  int64
 15  Accident_Location                         28117 non-null  object
 16  Accident_District                         28117 non-null  int64
 17  Accident_Location_Settlement              12340 non-null  object
 18  Transport_Category                        21668 non-null  object
 19  Public_Transport_Involved                 28117 non-null  int64
 20  Weather_Conditions                        19584 non-null  object
 21  Total_Number_of_Lanes                     28117 non-null  int64
 22  Speed_Limit                               28117 non-null  int64
 23  Number_of_Vehicles                        28117 non-null  int64
 24  Gender_of_At_Fault                        28117 non-null  int64
 25  Qualification_Code                        20647 non-null  object
 26  Accident_Type                             28117 non-null  int64
 27  Qualification_Description                 20647 non-null  object
 28  Road_Surface_Condition                    20616 non-null  object
 29  Highway_Index                             2207 non-null   object
 30  Road_Section                              3404 non-null   object
 31  Kilometer                                 28117 non-null  float64
 32  Year                                      28117 non-null  int32
 33  Month                                     28117 non-null  int32
 34  Day_of_Week                               28117 non-null  int32
 35  Time_of_day_of_accident_hrs               28117 non-null  int64
 36  Time_of_Day                               28117 non-null  int64
dtypes: datetime64[ns](1), float64(1), int32(3), int64(13), object(19)
memory usage: 7.6+ MB

In [28]:
df = df[df["Total_Number_of_Lanes"] != 20]

In [29]:
df["Lanes_Unknown"] = (df["Total_Number_of_Lanes"] == 0).astype(int)

In [31]:
from sklearn.preprocessing import MultiLabelBinarizer

df["Transport_Category"] = df["Transport_Category"].fillna("")
df["Transport_Category"] = df["Transport_Category"].apply(lambda x: x.split(",") if x != "" else [])

mlb = MultiLabelBinarizer()

encoded = pd.DataFrame(
    mlb.fit_transform(df["Transport_Category"]),
    columns=mlb.classes_,
    index=df.index
)

df = pd.concat([df, encoded], axis=1)

df["unknown_transport_category"] = df["Transport_Category"].apply(lambda x: 1 if x == [] else 0)

In [32]:
df = df.drop(columns=['Transport_Category'])

In [34]:
df["Condition_of_At_Fault_Person_Description"] = df["Condition_of_At_Fault_Person_Description"].fillna("unknown")
mapping = {
    1: "sober",
    2: "alcohol",
    3: "drugs",
    4: "toxic",
    5: "health_issue",
    6: "fatigue",
    "unknown": "unknown"
}

df["Condition_label"] = df["Condition_of_At_Fault_Person_Description"].map(mapping)
df = pd.get_dummies(df, columns=["Condition_label"], prefix="Faulty_Condition")

In [35]:
df = df.drop(columns=['Condition_of_At_Fault_Person_Description'])
df = df.drop(columns=['Condition_of_At_Fault_Person'])

In [37]:
df["Gender_of_At_Fault"] = df["Gender_of_At_Fault"].replace(0, "unknown")
mapping = {
    1: "male",
    2: "female",
    "unknown": "unknown"
}

df["Gender_label"] = df["Gender_of_At_Fault"].map(mapping)
df = pd.get_dummies(df, columns=["Gender_label"], prefix="At_Fault_Gender")
df = df.drop(columns=['Gender_of_At_Fault'])

In [39]:
import pandas as pd

# ---------------------------
# 1. Clean text safely (preserve NA)
# ---------------------------
df["At_Fault_Party"] = df["At_Fault_Party"].apply(
    lambda x: x.replace("\n", "").strip() if isinstance(x, str) else x
)

df["At_Fault_Party"] = df["At_Fault_Party"].apply(
    lambda x: " ".join(x.split()) if isinstance(x, str) else x
)

# ---------------------------
# 2. NA indicator
# ---------------------------
df["is_unknown"] = df["At_Fault_Party"].isna().astype(int)

# ---------------------------
# 3. Split into list (multi-label)
# ---------------------------
df["At_Fault_List"] = df["At_Fault_Party"].apply(
    lambda x: [i.strip().lower() for i in x.split(",")] if isinstance(x, str) else []
)

# ---------------------------
# 4. Define grouping logic
# ---------------------------
def check_any(lst, keywords):
    return int(any(any(k in item for k in keywords) for item in lst))


df["is_driver"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, [
        "водитель", 
        "имеющий водительские права"
    ])
)

df["is_pedestrian"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["пешеход"])
)

df["is_cyclist"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["велосипедист", "возчик"])
)

df["is_micro_mobility"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, [
        "самоката", 
        "электрического транспортного средства",
        "мопеда"
    ])
)

df["is_no_license"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["не имеющий водительских прав"])
)

df["is_deprived_license"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["лишенный водительских прав"])
)

df["is_minor"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["несовершеннолетний"])
)

df["is_foreign"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["иностранное лицо"])
)

df["escaped_scene"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["скрывшийся с места дтп"])
)

df["is_service_vehicle"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["специальной службы"])
)

df["is_special_worker"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, [
        "коммунальные службы",
        "дорожные службы",
        "подрядчики"
    ])
)

df["is_animal_owner"] = df["At_Fault_List"].apply(
    lambda x: check_any(x, ["хозяин животного"])
)

# ---------------------------
# 5. Drop helper columns
# ---------------------------
df.drop(columns=["At_Fault_Party", "At_Fault_List"], inplace=True)

In [46]:
df["Weather_Conditions"] = df["Weather_Conditions"].apply(
    lambda x: x.strip().lower() if isinstance(x, str) else x
)

# NA indicator (VERY IMPORTANT)
df["weather_unknown"] = df["Weather_Conditions"].isna().astype(int)

df["weather_clear"] = (df["Weather_Conditions"] == "ясно").astype(int)
df["weather_cloudy"] = (df["Weather_Conditions"] == "пасмурно").astype(int)
df["weather_rain"] = (df["Weather_Conditions"] == "дождь").astype(int)
df["weather_snow"] = (df["Weather_Conditions"] == "снег").astype(int)
df["weather_fog"] = (df["Weather_Conditions"] == "туман").astype(int)

In [48]:
df.drop(columns=["Weather_Conditions"], inplace=True)

In [49]:
import pandas as pd

# ---------------------------
# 1. Clean text safely
# ---------------------------
df["Road_Surface_Condition"] = df["Road_Surface_Condition"].apply(
    lambda x: x.strip().lower() if isinstance(x, str) else x
)

# ---------------------------
# 2. Missing indicator
# ---------------------------
df["road_surface_unknown"] = df["Road_Surface_Condition"].isna().astype(int)

# ---------------------------
# 3. Split multi-label
# ---------------------------
df["road_surface_list"] = df["Road_Surface_Condition"].apply(
    lambda x: [i.strip() for i in x.split(",")] if isinstance(x, str) else []
)

df["road_ice_snow_risk"] = df["road_surface_list"].apply(
    lambda x: int(any(i in x for i in [
        "заснеженная",
        "обледеневшая",
        "со снежным накатом"
    ]))
)

df["road_wet"] = df["road_surface_list"].apply(
    lambda x: int(any(i in x for i in ["мокрая"]))
)
df["road_dry"] = df["road_surface_list"].apply(
    lambda x: int(any(i in x for i in ["сухая"]))
)
df["road_under_construction"] = df["road_surface_list"].apply(
    lambda x: int(any(i in x for i in ["ремонт дорог"]))
)
df["road_dirty"] = df["road_surface_list"].apply(
    lambda x: int(any(i in x for i in ["загрязненная"]))
)
df["road_fresh_surface"] = df["road_surface_list"].apply(
    lambda x: int(any(i in x for i in ["свежеуложенная"]))
)

In [51]:
df.drop(columns=["Road_Surface_Condition", "road_surface_list"], inplace=True)

In [54]:
df["Lighting_Conditions"] = df["Lighting_Conditions"].apply(
    lambda x: x.strip().lower() if isinstance(x, str) else x
)

df["External_Lighting_at_Night"] = df["External_Lighting_at_Night"].apply(
    lambda x: x.strip().lower() if isinstance(x, str) else x
)
df["lighting_unknown"] = df["Lighting_Conditions"].isna().astype(int)
df["external_lighting_unknown"] = df["External_Lighting_at_Night"].isna().astype(int)
df["is_day"] = (df["Lighting_Conditions"] == "день").astype(int)
df["is_night"] = (df["Lighting_Conditions"] == "ночь").astype(int)
df["is_twilight"] = (df["Lighting_Conditions"] == "сумерки").astype(int)
df["light_on"] = (df["External_Lighting_at_Night"] == "включено").astype(int)
df["light_off"] = (df["External_Lighting_at_Night"] == "не включено").astype(int)
df["light_absent"] = (df["External_Lighting_at_Night"] == "отсутствует").astype(int)
df["night_without_lighting"] = (
    (df["is_night"] == 1) &
    (df["light_off"] == 1)
).astype(int)
df["twilight_without_lighting"] = (
    (df["is_twilight"] == 1) &
    (df["light_off"] == 1)
).astype(int)
df["lighting_data_missing_risk"] = (
    (df["lighting_unknown"] == 1) |
    (df["external_lighting_unknown"] == 1)
).astype(int)
df.drop(columns=["Lighting_Conditions", "External_Lighting_at_Night"], inplace=True)

In [57]:
df.drop(columns=["Qualification_Code", "Qualification_Description", "Road_Street_Elements", "Accident_Location_Settlement"], inplace=True)

In [60]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [64]:
location_mapping = {
    'на дороге': 1,
    'в населенном пункте': 2,
    'районного значения': 3,
    'областного значения': 4,
    'областного, районного значения': 5,
    'республиканского значения': 6,
    'международного, республиканского значения': 7
}
df['Accident_Location'] = df['Accident_Location'].map(location_mapping)

In [68]:
df.drop(columns=["Highway_Index", "Road_Section"], inplace=True)

In [69]:
import numpy as np

valid_speeds = np.array([30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 140])

def clean_speed(x):
    if x == 0:
        return 0  # keep unknown
    elif x < 30:
        return 30  # minimum realistic speed
    elif x in valid_speeds:
        return x  # already valid
    else:
        # round to nearest valid speed
        return valid_speeds[np.abs(valid_speeds - x).argmin()]

df['Speed_Limit_clean'] = df['Speed_Limit'].apply(clean_speed)
df[['Speed_Limit', 'Speed_Limit_clean']].drop_duplicates().sort_values('Speed_Limit')

       Speed_Limit  Speed_Limit_clean
0                0                  0
7793             1                 30
5999             2                 30
5821             4                 30
11581            6                 30
5429             8                 30
6706             9                 30
14259           10                 30
17054           11                 30
5468            20                 30
10648           27                 30
5583            30                 30
21619           34                 30
8454            39                 40
5364            40                 40
5390            50                 50
5361            60                 60
12191           61                 60
20752           62                 60
12270           68                 70
5378            70                 70
5351            80                 80
5422            89                 90
5357            90                 90
5520           100                100
5360           110                110
7300           120                120
16790          140                140

In [70]:
df.drop(columns=["Speed_Limit"], inplace=True)

In [72]:
df.drop(columns=["Traffic_Rule_Violation", "Registered_Road_Deficiencies_Description", "Recorded_Deficiencies"], inplace=True)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28103 entries, 0 to 28116
Data columns (total 89 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Type_of_Accident               28103 non-null  int64
 1   Accident_Date                  28103 non-null  datetime64[ns]
 2   Accident_Record_ID             28103 non-null  object
 3   Card_Number                    28103 non-null  int64
 4   Number_of_Injured              28103 non-null  int64
 5   Number_of_Fatalities           28103 non-null  int64
 6   Accident_Location              28103 non-null  int64
 7   Accident_District              28103 non-null  int64
 8   Public_Transport_Involved      28103 non-null  int64
 9   Total_Number_of_Lanes          28103 non-null  int64
 10  Number_of_Vehicles             28103 non-null  int64
 11  Accident_Type                  28103 non-null  int64
 12  Kilometer                      28103 non-null  float64
 13  Year                           28103 non-null  int32
 14  Month                          28103 non-null  int32
 15  Day_of_Week                    28103 non-null  int32
 16  Time_of_day_of_accident_hrs    28103 non-null  int64
 17  Time_of_Day                    28103 non-null  int64
 18  Lanes_Unknown                  28103 non-null  int64
 19  A                              28103 non-null  int64
 20  A1                             28103 non-null  int64
 21  B                              28103 non-null  int64
 22  B1                             28103 non-null  int64
 23  BE                             28103 non-null  int64
 24  C                              28103 non-null  int64
 25  C1                             28103 non-null  int64
 26  C1E                            28103 non-null  int64
 27  CE                             28103 non-null  int64
 28  D                              28103 non-null  int64
 29  D1                             28103 non-null  int64
 30  D1E                            28103 non-null  int64
 31  DE                             28103 non-null  int64
 32  E                              28103 non-null  int64
 33  M                              28103 non-null  int64
 34  R                              28103 non-null  int64
 35  T                              28103 non-null  int64
 36  Tb                             28103 non-null  int64
 37  Tm                             28103 non-null  int64
 38  W                              28103 non-null  int64
 39  X                              28103 non-null  int64
 40  unknown_transport_category     28103 non-null  int64
 41  Faulty_Condition_alcohol       28103 non-null  int64
 42  Faulty_Condition_drugs         28103 non-null  int64
 43  Faulty_Condition_fatigue       28103 non-null  int64
 44  Faulty_Condition_health_issue  28103 non-null  int64
 45  Faulty_Condition_sober         28103 non-null  int64
 46  Faulty_Condition_toxic         28103 non-null  int64
 47  Faulty_Condition_unknown       28103 non-null  int64
 48  At_Fault_Gender_female         28103 non-null  int64
 49  At_Fault_Gender_male           28103 non-null  int64
 50  At_Fault_Gender_unknown        28103 non-null  int64
 51  is_unknown                     28103 non-null  int64
 52  is_driver                      28103 non-null  int64
 53  is_pedestrian                  28103 non-null  int64
 54  is_cyclist                     28103 non-null  int64
 55  is_micro_mobility              28103 non-null  int64
 56  is_no_license                  28103 non-null  int64
 57  is_deprived_license            28103 non-null  int64
 58  is_minor                       28103 non-null  int64
 59  is_foreign                     28103 non-null  int64
 60  escaped_scene                  28103 non-null  int64
 61  is_service_vehicle             28103 non-null  int64
 62  is_special_worker              28103 non-null  int64
 63  is_animal_owner                28103 non-null  int64
 64  weather_unknown                28103 non-null  int64
 65  weather_clear                  28103 non-null  int64
 66  weather_cloudy                 28103 non-null  int64
 67  weather_rain                   28103 non-null  int64
 68  weather_snow                   28103 non-null  int64
 69  weather_fog                    28103 non-null  int64
 70  road_surface_unknown           28103 non-null  int64
 71  road_ice_snow_risk             28103 non-null  int64
 72  road_wet                       28103 non-null  int64
 73  road_dry                       28103 non-null  int64
 74  road_under_construction        28103 non-null  int64
 75  road_dirty                     28103 non-null  int64
 76  road_fresh_surface             28103 non-null  int64
 77  lighting_unknown               28103 non-null  int64
 78  external_lighting_unknown      28103 non-null  int64
 79  is_day                         28103 non-null  int64
 80  is_night                       28103 non-null  int64
 81  is_twilight                    28103 non-null  int64
 82  light_on                       28103 non-null  int64
 83  light_off                      28103 non-null  int64
 84  light_absent                   28103 non-null  int64
 85  night_without_lighting         28103 non-null  int64
 86  twilight_without_lighting      28103 non-null  int64
 87  lighting_data_missing_risk     28103 non-null  int64
 88  Speed_Limit_clean              28103 non-null  int64
dtypes: datetime64[ns](1), float64(1), int32(3), int64(83), object(1)
memory usage: 19.0+ MB

In [74]:
df.to_csv("jestka_preprocessed_dataset.csv", index=False)

In [1]:
df.info()

NameError: name 'df' is not defined